[workspace]
members = [
	"aesm-client",
	"dcap-ql-sys",
	"dcap-ql",
	"enclave-runner",
	"fortanix-sgx-tools",
	"report-test",
	"sgx-isa",
	"sgxs",
	"sgxs-tools",
	"fortanix-sgx-abi",
	"sgxs-loaders"
]
